### PR TITLE
Removes jQuery dependency for AutoSuggest

### PR DESCRIPTION
**Pull request by AmyShackles**

### CODE REVIEW

**Comment by weboverhauls** [comment]
This is great, thank you!
One issue though, when spacebar is pressed when dropdown not displayed, a JS error occurs.
image

**Comment by AmyShackles** [comment]
Sorry about that, totally forgot to update this PR after I'd discovered that bug on my React version.  Should be fixed now.

I do have a question, though.  Neither your version nor this one update the options when the text entered no longer generates matches — is that intentional behavior or should it be updated so that the announcement message indicates the lack of matches and the dropdown removes the previously matched items?

**Comment by weboverhauls** [comment]
Hmm...still seeing a JS error when pressing spacebar.
Not sure if it's related, but there's also a grey line below the input which wasn't present previously.
image

About your question, I believe that was the original functionality. Seems like a matter of preference. Without usability testing I don't see any reason to change it.

**Comment by AmyShackles** [comment]
Good catch with the grey bar.  Definitely had logic that should have toggled display to none and was instead toggling it to block.  I also absolutely forgot to do some of the aria setup in the init() function.  

The error should be fixed now.  Behavior of arrowing down through the options should result in a circular loop rather than having a non-selected break between the first and last items in the list.  Grey bar should now also be gone.

Hope this helps!

**Comment by weboverhauls** [comment]
Appears fixed, thank you so much!

**Comment by weboverhauls** [comment]
@AmyShackles Also, if you used this code for react-autosuggestions, would you please provide credit in the ReadMe? Thanks again for your PR.

**Pull request merged**
